My branch
csarat/amazon-snowflake pull request #2
Opened 2024-04-23 19:51 UTC by NagasairamM

please verify the code and update in the main branch.

2024-04-23 19:54 UTC, csarat requested changes
Left comments

2024-04-23 19:54 UTC, csarat commented on main.tf
> +  privileges        = ["USAGE"]
Why did we give `usage` privileges here?

2024-04-23 19:54 UTC, csarat commented on main.tf
>      schema_name = "\"${snowflake_database.db.name}\".\"${snowflake_schema.schema.name}\""
Why do we have to escape quotes here? Why can't we directly reference the resource instance?

2024-04-24 18:31 UTC, NagasairamM commented on main.tf
>      schema_name = "\"${snowflake_database.db.name}\".\"${snowflake_schema.schema.name}\""
Actually, I tried that. it showing a syntax error. so bought it from documentation.

2024-04-26 06:28 UTC, NagasairamM reviewed
Please review the code.

2024-04-26 14:30 UTC, csarat commented on main.tf
> +  privileges        = ["USAGE"]
questions should be responded here and should resolve the conversation here

2024-04-26 14:30 UTC, csarat approved these changes
LGTM

2024-04-27 18:26 UTC, merged