update1
csarat/amazon-snowflake pull request #4
Opened 2024-04-30 17:37 UTC by NagasairamM

Please review and approve the PR

2024-04-30 19:45 UTC, csarat commented on main.tf
> +resource "snowflake_role" "role1" {
Give proper names to the resources

2024-04-30 19:45 UTC, csarat requested changes
Give proper names to all the terraform resource names

2024-04-30 19:50 UTC, csarat commented
Give proper title to the PR. `<Jira#>: <overall description of the PR>` for example for this PR `TFSNOW-10: Creating __AMAZON_ORDERS_USG usage role`. This can still be changed.

Commit message should be description of that commit with the format `<Jira#>: <message>` for example `TFSNOW-10: Creating usage role`. This is FYI. you cannot change this anymore.

2024-05-01 14:55 UTC, NagasairamM commented
Creating __AMAZON_ORDERS_USG usage role;
Based on the given suggestions the code has been changed and raised request again. please review and approve the PR

2024-05-01 16:07 UTC, csarat requested changes
Check my comments

2024-05-01 16:07 UTC, csarat commented on main.tf
> +resource "snowflake_database" "amazon_db1" {
This is much better. `amazon_db` makes more sense. 
Why is `1` required here?

2024-05-01 16:07 UTC, csarat commented on main.tf
> +resource "snowflake_grant_privileges_to_account_role" "schema_grant" {
can you come up with a better name instead of `schema_grant`

2024-05-02 19:47 UTC, NagasairamM commented
Update the code according to the given preferences! please review and approve the PR.

2024-05-02 20:43 UTC, NagasairamM commented on main.tf
> +resource "snowflake_grant_privileges_to_account_role" "schema_grant" {
I think schema_grant word makes more sense.

2024-05-02 23:08 UTC, NagasairamM commented on main.tf
> +resource "snowflake_database" "amazon_db1" {
please find the new updated with name.

2024-05-03 02:12 UTC, NagasairamM commented
The code was updated based on the given suggestions, Please review the code.

2024-05-03 04:01 UTC, NagasairamM commented
Please review the code.

2024-05-03 04:07 UTC, csarat approved these changes

2024-05-03 04:07 UTC, merged